---
title: "R Notebook"
output: html_notebook
---


```{r}
#read file and libraries
infile = "otu_sample_value.txt"
library("Matrix")  # sparseMatrix()
d = read.table(infile, header=T, sep="\t", colClasses=c(rep("character", 2), "numeric"))
otus = read.table("row_metadata.txt", header=T, sep="\t", colClasses=rep("character", 9))
samples = read.table("column_metadata.txt", header=T, sep="\t", colClasses=rep("character", 2))

# extract row / column indices
I = as.integer(gsub("otu_", "", d$OTU)) + 1        # add 1 to convert 0-index to 1-index
J = as.integer(gsub("sample_", "", d$SAMPLE)) + 1  # add 1 to convert 0-index to 1-index
```

```{r}
# sparse bipartitie OTU-sample adjacency matrix (w/o filtering)
A = sparseMatrix(i=I, j=J, x=d$VALUE)
rownames(A) = otus$ID
colnames(A) = samples$ID
dim(A)
##here, just want to see if there's a difference aftering taking sqrt transformation
#take sqrt transformation(stablization)
A.sqrt=A
A.sqrt@x=sqrt(A.sqrt@x)
plot(A@x)
plot(A.sqrt@x)

#plot out-degree to examine
hist(log10(rowSums(A)))#highly skewed, some microbiomes are more abundant than others
```

```{r, message=FALSE}
#do vsp on A (the adjacency matrix), not very useful lol, just a trial
library(vsp)
library(dplyr)
fa_A<-vsp(A, rank=50)
plot_varimax_z_pairs(fa_A,1:10)#row(otu)
plot_varimax_y_pairs(fa_A,1:10)#colum(sample)
screeplot(fa_A)
```

```{r}
#Adjacency matrix with 1, 0 entries(the row sum can be useful for subsetting the sample)
#but I think using the original adjacency matrix(A) to do analysis is more informative
#because the absolute vaule of otus in each sample is related with beta diversity
#sample with similar beta diversity should be grouped together
A.simple=(A > 0) * 1

#pick a managable number of OTUs to manipulate the OTU co-occurrence network
#Pick OTUs that belong to a few prominent phyla
selected.otus = rbind(
  subset(otus, otus$PHYLUM == "p__Proteobacteria", ID),
  subset(otus, otus$PHYLUM == "p__Bacteroidetes", ID),
  subset(otus, otus$PHYLUM == "p__Firmicutes", ID)
)

#index for prominent phyla
idx.phy = as.numeric(row.names(selected.otus))
##subset the true-val Adjacency matrix (A->A.sel)
A.sel=A[idx.phy,]
##subset the simple Adjacency matrix(A.simple)
A.simple=A.simple[idx.phy,]

#index of OTUs with prevalence of at least 10 samples(use the rowSum of A.simple to pick)
#since A.simple records 1 in Aij if otui appears in sample j; 0 otherwise
idx.prv = rowSums(A.simple) > 9
##continue to subset the true-val Adjacency matrix
A.sel=A.sel[idx.prv,]
##continue to subset the simple Adjacency matrix(because the rowSum of this matrix might be useful later), and I want to make sure the dimension matches the true-val Adj matrix
A.simple=A.simple[idx.prv,]

#Order matrix rows by prevalence, high to low
o = order(rowSums(A.simple), decreasing=T)
A.simple = A.simple[o,]
prevalence = rowSums(A.simple)  # handy to use this later

#look at A.sel
A.sel[1:10,1:10]
dim(A.sel)

```

```{r}
#take square root transformation on A.sel (the adjmatrix of interest)
A.sel@x=sqrt(A.sel@x)
#look at A.sel again
A.sel[1:10,1:10]
```
## Do vsp on data of interest, matrix: A.sel(an adjacency matrix, row: otu; col: sample)  
```{r,message=FALSE}
#do vsp on A.sel 
fa_A.sel<-vsp(A.sel, rank=10)
#fa_A.sel<-vsp(A.sel, rank=30, center = TRUE)
#see the top 10 in each flocak
apply(fa_A.sel$Y,2, function(x) samples$SAMPLE[order(-x)[1:100]])
plot_varimax_z_pairs(fa_A.sel,1:10)#row(otu)
plot_varimax_y_pairs(fa_A.sel,1:10)#colum(sample)
screeplot(fa_A.sel)
dim(fa_A.sel$Z)#otu loadings in each flock, a column is a flock.
dim(fa_A.sel$Y)#sample loadings in each flock, a column is a flock.

colSums(fa_A.sel$v^2)#about sample, v is orthonormal, colSums=1
colSums(fa_A.sel$u^2)#about otu, u is orthonormal, colSums=1
hist(log10(fa_A.sel$u^2))
hist(log10(fa_A.sel$u[,1]^2))#(estimating log probability distribution of otus within the 1st topic?)
sum(fa_A.sel$v[1,]^2)
hist(log10(fa_A.sel$v^2))#(log probability distribution of samples within each of the k topics?)
```

## plot sample-flock, and encode with empo_3
```{r, message=FALSE}
library(ggplot2)
library(dplyr)
#ggallery ref: https://www.r-graph-gallery.com/199-correlation-matrix-with-ggally.html
sample_meta = read.table("sample_metadata_detail.txt", header=T, sep="\t", colClasses=rep("character", 76))
#sample_flocklaoad<-fa_A.sel$Y
sample_flocklaoad<-fa_center$Y
rownames(sample_flocklaoad)<-samples$SAMPLE
apply(sample_flocklaoad,2, function(x) samples$SAMPLE[order(-x)[1:100]])%>%View

sample_flocklaoad
fa_A.sel$Y
sample_meta_ofInterest=sample_meta%>%select(X.SampleID,empo_3)%>%rename(SAMPLE=X.SampleID)
#plot varimax y pairs with empo encoding
fa_A.sel%>%
  get_varimax_y(1:5)%>%
  select(-id) %>%
  mutate(leverage = purrr::pmap_dbl(., sum))%>%
  mutate(SAMPLE=samples$SAMPLE)%>%
  left_join(sample_meta_ofInterest)%>%
  #there's not so much to sample if only use a few factors to plot, eg. no need to sample when we use less than 5 factors to plot
  #sample_n(min(nrow(.), 1000), weight = leverage^2)%>%
  #select(-leverage,-SAMPLE)%>%
  #select(-SAMPLE)%>%
  GGally::ggpairs(columns=1:5,ggplot2::aes(colour=empo_3),cardinality_threshold = 17) +
  theme_minimal()

fa_A.sel%>%
  get_varimax_y(6:10)%>%
  select(-id) %>%
  mutate(leverage = purrr::pmap_dbl(., sum))%>%
  mutate(SAMPLE=samples$SAMPLE)%>%
  left_join(sample_meta_ofInterest)%>%
  #there's not so much to sample if only use a few factors to plot, eg. no need to sample when we use less than 5 factors to plot
  #sample_n(min(nrow(.), 1000), weight = leverage^2)%>%
  #select(-leverage,-SAMPLE)%>%
  #select(-SAMPLE)%>%
  GGally::ggpairs(columns=1:5,ggplot2::aes(colour=empo_3),cardinality_threshold = 17) +
  theme_minimal()

```


## Characterize sample's clusters (i.e. examine what kind of environments may have similar microbiome community pattern)
```{r, message=FALSE}
library(dplyr)
library(vsp)
library(tidytext)
#read in sample metadata
#76 col
sample_meta = read.table("sample_metadata_detail.txt", header=T, sep="\t", colClasses=rep("character", 76))
sample_meta_ofInterest=sample_meta%>%select(X.SampleID,env_feature,env_biome)%>%rename(SAMPLE=X.SampleID)
#sample_meta_ofInterest=sample_meta%>%select(X.SampleID,empo_3)%>%rename(SAMPLE=X.SampleID)
sample_meta_ID=samples%>%left_join(sample_meta_ofInterest)%>%select(-SAMPLE)%>%mutate(ID=(0:1999))
sample_meta_mtx=cast_sparse(sample_meta_ID,ID,env_feature)
sample_meta_mtx2=cast_sparse(sample_meta_ID,ID,env_biome)
#unnest the feature words into feature word tokens
#meta_tt=sample_meta_ID%>%unnest_tokens(env_featkey,env_feature)
#meta_tt_mtx=cast_sparse(meta_tt,ID,env_featkey)
#sample_meta_mtx=cast_sparse(sample_meta_ID,ID,empo_3)

dim(sample_meta_mtx)
dim(sample_meta_mtx2)
#characterize 
feature= bff(fa_A.sel$Y, sample_meta_mtx,20)
biome= bff(fa_A.sel$Y, sample_meta_mtx2,20)
biome= bff(fa_center$Y, sample_meta_mtx2,20)
#feature= bff(fa_A.sel$Y, meta_tt_mtx,10)
feature
biome
```
          
             
             
             